--create database practice;
--use Practice;
create table ALL_TEST1(TEST_CODE varchar (10),TST_TYPE char(10));
create table Test_TBL1(TEST_ID INT,TEST_NAME VARCHAR (20),TEST_CODE VARCHAR(20),TEST_STATE CHAR(2),TEST_SUBJ_CODE CHAR(4),TEST_SUBJ_MARKS INT);
CREATE TABLE ALL_TEST2(TEST_CODE VARCHAR(10) PRIMARY KEY,TEST_DOMAIN VARCHAR(20) NOT NULL,TEST_TYPE CHAR(10) NOT NULL);

CREATE TABLE TEST_TBL2(TEST_ID INT PRIMARY KEY,TEST_NAME VARCHAR(20)NOT NULL,TEST_CODE VARCHAR(10) FOREIGN KEY REFERENCES ALL_TEST2(TEST_CODE),TEST_STATE CHAR(2),TEST_SUBJ_CODE CHAR (4) UNIQUE,TEST_SUBJ_MARKS INT CHECK(TEST_SUBJ_MARKS < 100));
--DROP TABLE TEST_TBL2;
CREATE TABLE ALL_TEST3(TEST_CODE VARCHAR (10) CONSTRAINT TC_PK PRIMARY KEY, TEST_DOMAIN VARCHAR(10) CONSTRAINT TC_NN NOT NULL,TEST_TYPE VARCHAR (10) CONSTRAINT TT_NN NOT NULL);
CREATE TABLE TEST_TBL3(TEST_ID INT CONSTRAINT TI_PK PRIMARY KEY,TEST_NAME VARCHAR(20) CONSTRAINT TN_NN NOT NULL,TEST_CODE VARCHAR(10) CONSTRAINT TC_FK FOREIGN KEY REFERENCES ALL_TEST2(TEST_CODE),TEST_STATE CHAR(2),
TEST_SUBJ_CODE CHAR (4)CONSTRAINT TSC_UNQ UNIQUE,TEST_SUBJ_MARKS INT CONSTRAINT TSM_CHK CHECK(TEST_SUBJ_MARKS < 100));
CREATE TABLE ALL_TEST4  into ALL_TEST1; ---- this command shows error
SELECT * INTO ALL_TEST4  FROM ALL_TEST1;--- Correct command


