//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schema_First_Approch_Practice3
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Product")]
    public partial class Project_Product_table
    {
        public int Id { get; set; }
        public string Productname { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> MFD { get; set; }
        public Nullable<int> catid { get; set; }
    
        public virtual Project_Category_table Project_Category_table { get; set; }
    }
}
